name: linkedin_login
description: App for demonstrating LinkedIn Login.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  webview_flutter: ^0.3.19+7
  font_awesome_flutter: ^8.7.0
  flutter_secure_storage: ^3.3.1+1
  retrofit: ^1.3.0
  dio: ^3.0.8

  json_serializable: ^3.2.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  retrofit_generator: ^1.3.0
  build_runner:



flutter:
  assets:
    - assets/images/menu.png
    
  uses-material-design: true